routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::resource('pemilik', 'PemilikController');
    Route::resource('mobil', 'MobilController');
    Route::get('/home', 'HomeController@index')->name('home');

});

app/Mobil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mobil extends Model
{
     //nama tabel
     protected $table = "mobils";

     //nama kolom
     protected $fillable = ['kode','tahun','warna','no_plat','no_mesin','no_rangka','status_mobil','merk','tipe','foto','pemilik_id'];

     //relasi ke tabel pemilik
     public function pemilik()
     {
     	return $this->belongsTo('App\Pemilik');
     }

     public function getStatusMobilFormatted() {
          if($this->getAttribute('status_mobil') == 0) {
              return "Tersedia";
          }else {
              return "Tidak Tersedia";
          }
     }
}

app/Http/Controllers/MobilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mobil;
use App\Pemilik;
class MobilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //ambil semua data dari tabel mobil di database
        $data = Mobil::all();

        //tampilkan dan arahkan ke halaman index
        return view('mobil.index', compact ('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //tampilkan data pemilik
        $pemilik = Pemilik::all();

        return view('mobil.create', compact('pemilik'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         //cek data foto
         $request->validate([
            'foto' => 'required|image|mimes:jpg,png,jpeg|max:2048',
        ]);
    
        //save data ke database, 'Mobil' adalah nama model
        Mobil::create([
            'kode' => $request->kode,
            'tahun' => $request->tahun,
            'warna' => $request->warna,
            'no_plat' => $request->no_plat,
            'no_mesin' => $request->no_mesin,
            'no_rangka' => $request->no_rangka,
            'status_mobil' => $request->status_mobil,
            'merk' => $request->merk,
            'tipe' => $request->tipe,
            'pemilik_id' => $request->pemilik_id,
            'foto' => $this->saveImage($request->file('foto'))
        ]);

        //arahkan ke halaman mobil dan tampilkan pesan/status
        return redirect('/mobil')->with('status', 'Data Berhasil Ditambah');
    }

    //fungsi untuk menyimpan data foto
    public function saveImage($file)
    {
       $name = \Carbon\Carbon::now()->format('Y-m-dH:i:s').'-' .$file->getClientOriginalName(). '.' . $file->getClientOriginalExtension();
     
       $path = $file->storeAs('/public/images', $name);
       return $name; 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         //tampilkan data berdasarkan $id data
         $data = Mobil::findOrFail($id);

         //arahkan dan tampilkan data pada halaman edit
         return view('mobil.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //tampilkan data pemilik
        $pemilik = Pemilik::all();
        
        //tampilkan data berdasarkan $id data
        $data = Mobil::findOrFail($id);

        //arahkan dan tampilkan data pada halaman edit
        return view('mobil.edit', compact('data','pemilik'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         //cek data foto
         $request->validate([
            'foto' => 'image|mimes:jpg,png,jpeg|max:2048',
        ]);

        $mobil = Mobil::findOrFail($id);
            
        //jika foto kosong maka foto yang di save adalah foto lama
        if($request->file('foto') == null) {
           $request->foto = $mobil->foto;
        }
        else{
           $request->foto = $this->saveImage($request->file('foto'));
        }
       
        Mobil::where('id', $id)
                ->update([
                    'kode' => $request->kode,
                    'tahun' => $request->tahun,
                    'warna' => $request->warna,
                    'no_plat' => $request->no_plat,
                    'no_mesin' => $request->no_mesin,
                    'no_rangka' => $request->no_rangka,
                    'status_mobil' => $request->status_mobil,
                    'merk' => $request->merk,
                    'tipe' => $request->tipe,
                    'pemilik_id' => $request->pemilik_id,
                    'foto' => $request->foto
                ]);

        return redirect('/mobil')->with('status', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         //hapus data berdasarkan $id
         Mobil::destroy($id);

         //arahkan ke halaman mobil dan tampilkan pesan/status
         return redirect('/mobil')->with('status', 'Data Berhasil Dihapus');
    }
}

resources/views/mobil/create.blade.php
@extends('layouts.app')

{{-- isi @yield('content') --}}
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah Data</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="card-body">
                        <form method="POST" action="{{ route('mobil.store') }}"  enctype="multipart/form-data">
                            @csrf
                            
                            <div class="form-group row">
                                <label for="kode" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode</label>
    
                                <div class="col-md-6">
                                    <input id="kode" type="text" class="form-control @error('kode') is-invalid @enderror" name="kode" value="{{ old('kode') }}" required autocomplete="kode" autofocus>
    
                                    @error('kode')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    

                            <div class="form-group row">
                                <label for="tahun" class="col-md-3 offset-md-1 col-form-label text-md-left">Tahun</label>
    
                                <div class="col-md-6">
                                    <input id="tahun" type="text" class="form-control @error('tahun') is-invalid @enderror" name="tahun" value="{{ old('tahun') }}" required autocomplete="tahun" autofocus>
    
                                    @error('tahun')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="warna" class="col-md-3 offset-md-1 col-form-label text-md-left">Warna</label>
    
                                <div class="col-md-6">
                                    <input id="warna" type="warna" class="form-control @error('warna') is-invalid @enderror" name="warna" value="{{ old('warna') }}" required autocomplete="warna">
    
                                    @error('warna')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="no_plat" class="col-md-3 offset-md-1 col-form-label text-md-left">No Plat</label>
    
                                <div class="col-md-6">
                                    <input id="no_plat" type="no_plat" class="form-control @error('no_plat') is-invalid @enderror" name="no_plat" value="{{ old('no_plat') }}" required autocomplete="no_plat">
    
                                    @error('no_plat')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="no_mesin" class="col-md-3 offset-md-1 col-form-label text-md-left">No Mesin</label>
    
                                <div class="col-md-6">
                                    <input id="no_mesin" type="no_mesin" class="form-control @error('no_mesin') is-invalid @enderror" name="no_mesin" value="{{ old('no_mesin') }}" required autocomplete="no_mesin">
    
                                    @error('no_mesin')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="no_rangka" class="col-md-3 offset-md-1 col-form-label text-md-left">No Rangka</label>
    
                                <div class="col-md-6">
                                    <input id="no_rangka" type="no_rangka" class="form-control @error('no_rangka') is-invalid @enderror" name="no_rangka" value="{{ old('no_rangka') }}" required autocomplete="no_rangka">
    
                                    @error('no_rangka')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status_mobil" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode Pos</label>
    
                                <div class="col-md-6">
                                    <select name="status_mobil" id="" class="form-control @error('status_mobil') is-invalid @enderror" required >
                                        <option value="0">Tersedia</option>
                                        <option value="1">Tidak Tersedia</option>
                                    </select>
                           
                                    @error('status_mobil')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="merk" class="col-md-3 offset-md-1 col-form-label text-md-left">Merk</label>
    
                                <div class="col-md-6">
                                    <input id="merk" type="merk" class="form-control @error('merk') is-invalid @enderror" name="merk" value="{{ old('merk') }}" required autocomplete="new-merk">
    
                                    @error('merk')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="tipe" class="col-md-3 offset-md-1 col-form-label text-md-left">Tipe</label>
    
                                <div class="col-md-6">
                                    <input id="tipe" type="tipe" class="form-control @error('tipe') is-invalid @enderror" name="tipe" value="{{ old('tipe') }}" required autocomplete="new-tipe">
    
                                    @error('tipe')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="foto" class="col-md-3 offset-md-1 col-form-label text-md-left">Foto</label>
    
                                <div class="col-md-6">
                                    <input id="foto" type="file" class="form-control @error('foto') is-invalid @enderror" name="foto" value="{{ old('foto') }}" required autocomplete="new-foto">
    
                                    @error('foto')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="pemilik_id" class="col-md-3 offset-md-1 col-form-label text-md-left">Pemilik</label>
    
                                <div class="col-md-6">

                                    <select name="pemilik_id" id="pemilik_id" class="form-control">
                                        @foreach ($pemilik as $p)
                                            <option value="{{$p->id}}"> {{ $p->nama }}</option>
                                        @endforeach
                                    </select>
    
                                    @error('pemilik_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                        
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Tambah
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mobil/edit.blade.php
@extends('layouts.app')

{{-- isi @yield('content') --}}
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Data</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="card-body">
                            <form method="POST" action="{{ "/mobil/$data->id" }}"  enctype="multipart/form-data">
                                @method('put')
                                @csrf
                                
                                <div class="form-group row">
                                    <label for="kode" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode</label>
        
                                    <div class="col-md-6">
                                        <input id="kode" type="text" class="form-control @error('kode') is-invalid @enderror" name="kode" value="{{ $data->kode }}" required autocomplete="kode" autofocus>
        
                                        @error('kode')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
        
    
                                <div class="form-group row">
                                    <label for="tahun" class="col-md-3 offset-md-1 col-form-label text-md-left">Tahun</label>
        
                                    <div class="col-md-6">
                                        <input id="tahun" type="text" class="form-control @error('tahun') is-invalid @enderror" name="tahun" value="{{ $data->tahun }}" required autocomplete="tahun" autofocus>
        
                                        @error('tahun')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
        
                                <div class="form-group row">
                                    <label for="warna" class="col-md-3 offset-md-1 col-form-label text-md-left">Warna</label>
        
                                    <div class="col-md-6">
                                        <input id="warna" type="warna" class="form-control @error('warna') is-invalid @enderror" name="warna" value="{{ $data->warna }}" required autocomplete="warna">
        
                                        @error('warna')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="no_plat" class="col-md-3 offset-md-1 col-form-label text-md-left">No Plat</label>
        
                                    <div class="col-md-6">
                                        <input id="no_plat" type="no_plat" class="form-control @error('no_plat') is-invalid @enderror" name="no_plat" value="{{ $data->no_plat }}" required autocomplete="no_plat">
        
                                        @error('no_plat')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="no_mesin" class="col-md-3 offset-md-1 col-form-label text-md-left">No Mesin</label>
        
                                    <div class="col-md-6">
                                        <input id="no_mesin" type="no_mesin" class="form-control @error('no_mesin') is-invalid @enderror" name="no_mesin" value="{{ $data->no_mesin }}" required autocomplete="no_mesin">
        
                                        @error('no_mesin')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label for="no_rangka" class="col-md-3 offset-md-1 col-form-label text-md-left">No Rangka</label>
        
                                    <div class="col-md-6">
                                        <input id="no_rangka" type="no_rangka" class="form-control @error('no_rangka') is-invalid @enderror" name="no_rangka" value="{{ $data->no_rangka }}" required autocomplete="no_rangka">
        
                                        @error('no_rangka')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="status_mobil" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode Pos</label>
        
                                    <div class="col-md-6">
                                        <select name="status_mobil" id="" class="form-control @error('status_mobil') is-invalid @enderror" required >
                                            <option value="0">Tersedia</option>
                                            <option value="1">Tidak Tersedia</option>
                                        </select>
                               
                                        @error('status_mobil')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
    
                                <div class="form-group row">
                                    <label for="merk" class="col-md-3 offset-md-1 col-form-label text-md-left">Merk</label>
        
                                    <div class="col-md-6">
                                        <input id="merk" type="merk" class="form-control @error('merk') is-invalid @enderror" name="merk" value="{{ $data->merk }}" required autocomplete="new-merk">
        
                                        @error('merk')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
    
                                <div class="form-group row">
                                    <label for="tipe" class="col-md-3 offset-md-1 col-form-label text-md-left">Tipe</label>
        
                                    <div class="col-md-6">
                                        <input id="tipe" type="tipe" class="form-control @error('tipe') is-invalid @enderror" name="tipe" value="{{ $data->tipe }}" required autocomplete="new-tipe">
        
                                        @error('tipe')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
    
                                <div class="form-group row">
                                    <label for="foto" class="col-md-3 offset-md-1 col-form-label text-md-left">Foto</label>
        
                                    <div class="col-md-6">
                                        <input id="foto" type="file" class="form-control @error('foto') is-invalid @enderror" name="foto" value="{{ $data->foto }}" autocomplete="new-foto">
        
                                        @error('foto')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
    
                                <div class="form-group row">
                                    <label for="pemilik_id" class="col-md-3 offset-md-1 col-form-label text-md-left">Pemilik</label>
        
                                    <div class="col-md-6">
                                            <select name="pemilik_id" id="pemilik_id" class="form-control">
                                                @foreach ($pemilik as $p)
                                                    <option value="{{$p->id}}" @if($data->pemilik_id == $p->id) selected @endif  > {{ $p->nama }}</option>
                                                @endforeach
                                            </select>
        
                                        @error('pemilik_id')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
        
                            
                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            Update
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mobil/index.blade.php
@extends('layouts.app')

{{-- isi @yield('content') --}}
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">List Data</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="row text-right">
                        <div class="col-lg-12">
                            <a href="/mobil/create" class="btn btn-primary btn-sm">
                              Tambah Data
                            </a>
                        </div>
                    </div>

                    <div class="row ml-1">   
                        <table border=1 cellpadding="10">
                            <thead style="text-align:center">
                                <th>No</th>
                                <th>Kode</th>
                                <th>Tahun</th>
                                <th>Warna</th>
                                <th>Pemilik</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </thead>
                            <tbody>
                            @foreach ($data as $dt)
                                <tr>
                                    <td>{{ $loop->iteration }} </td>   
                                    <td>{{ $dt->kode }} </td>   
                                    <td>{{ $dt->tahun }} </td>   
                                    <td>{{ $dt->warna }} </td>   
                                    <td>{{ $dt->pemilik->nama }} </td>   
                                    <td>{{ $dt->status_mobil_formatted }} </td>   
                                    
                                    <td>
                                      <a href={{"mobil/$dt->id/edit"}} class="btn btn-warning btn-sm">Edit</a> 
                                      <form action={{"/mobil/$dt->id"}} method="POST" class="d-inline">
                                        @method('delete')
                                        @csrf
                                          <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Yakin?')">Hapus</button>
                                      </form>
                                      <a href={{"mobil/$dt->id"}} class="btn btn-primary btn-sm" >Detail</a>
                                    </td>  
                                </tr> 
                            @endforeach  
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection