routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::resource('pemilik', 'PemilikController');
    Route::resource('mobil', 'MobilController');
    Route::get('/home', 'HomeController@index')->name('home');

});

app/Pemilik.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pemilik extends Model
{
    //nama tabel
    protected $table = "pemiliks";

    //nama kolom
    protected $fillable = ['nama', 'alamat', 'kelurahan', 'kecamatan', 'kab_kota', 'kode', 'kode_pos', 'telp'];

    //relasi ke tabel mobil, 1 pemilik dapat memiliki banyak mobil
    public function mobils(){
    	return $this->hasMany('App\Mobil','pemilik_id');
    }
    
}

app/Http/Controllers/PemilikController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

// hubungkan model pemilik dengan controller pemilik
use App\Pemilik;
class PemilikController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //ambil semua data dari tabel pemilik di database
        $data = Pemilik::all();

        //tampilkan dan arahkan ke halaman index
        return view('pemilik.index', compact ('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //arahkan ke halaman create
        return view('pemilik.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //cek data telepon, required = tidak boleh kosong, ,max:12 = karakter yang diinputkan tidak boleh lebih dari 12
        $request->validate([
            'telp' => 'required|max:12',
        ]);
    
        //save data ke database, 'Pemilik' adalah nama model
        Pemilik::create([
            'nama' => $request->nama,
            'alamat' => $request->alamat,
            'kelurahan' => $request->kelurahan,
            'kecamatan' => $request->kecamatan,
            'kab_kota' => $request->kab_kota,
            'kode' => $request->kode,
            'kode_pos' => $request->kode_pos,
            'telp' => $request->telp,
        ]);

        //arahkan ke halaman pemilik dan tampilkan pesan/status
        return redirect('/pemilik')->with('status', 'Data Berhasil Ditambah');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //tampilkan data berdasarkan $id data
        $data = Pemilik::findOrFail($id);

        //arahkan dan tampilkan data pada halaman edit
        return view('pemilik.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //tampilkan data berdasarkan $id data
        $data = Pemilik::findOrFail($id);

        //arahkan dan tampilkan data pada halaman edit
        return view('pemilik.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //cek data telepon yang diinputkan, required = tidak boleh kosong, ,max:12 = karakter yang diinputkan tidak boleh lebih dari 12
        $request->validate([
            'telp' => 'required|max:12',
        ]);
            
        //update data berdasarkan id
        Pemilik::where('id', $id)
                ->update([
                    'nama' => $request->nama,
                    'alamat' => $request->alamat,
                    'kelurahan' => $request->kelurahan,
                    'kecamatan' => $request->kecamatan,
                    'kab_kota' => $request->kab_kota,
                    'kode' => $request->kode,
                    'kode_pos' => $request->kode_pos,
                    'telp' => $request->telp,
                    ]);
        
        //arahkan ke halaman pemilik dan tampilkan pesan/status
        return redirect('/pemilik')->with('status', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //hapus data berdasarkan $id
        Pemilik::destroy($id);

        //arahkan ke halaman pemilik dan tampilkan pesan/status
        return redirect('/pemilik')->with('status', 'Data Berhasil Dihapus');
    }
}

resources/views/pemilik/create.blade.php
@extends('layouts.app')

{{-- isi @yield('content') --}}
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah Data</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="card-body">
                        <form method="POST" action="{{ route('pemilik.store') }}">
                            @csrf
                            
                            <div class="form-group row">
                                <label for="kode" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode</label>
    
                                <div class="col-md-6">
                                    <input id="kode" type="text" class="form-control @error('kode') is-invalid @enderror" name="kode" value="{{ old('kode') }}" required autocomplete="kode" autofocus>
    
                                    @error('kode')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    

                            <div class="form-group row">
                                <label for="nama" class="col-md-3 offset-md-1 col-form-label text-md-left">Nama</label>
    
                                <div class="col-md-6">
                                    <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}" required autocomplete="nama" autofocus>
    
                                    @error('nama')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="alamat" class="col-md-3 offset-md-1 col-form-label text-md-left">Alamat</label>
    
                                <div class="col-md-6">
                                    <input id="alamat" type="alamat" class="form-control @error('alamat') is-invalid @enderror" name="alamat" value="{{ old('alamat') }}" required autocomplete="alamat">
    
                                    @error('alamat')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="kelurahan" class="col-md-3 offset-md-1 col-form-label text-md-left">kelurahan</label>
    
                                <div class="col-md-6">
                                    <input id="kelurahan" type="kelurahan" class="form-control @error('kelurahan') is-invalid @enderror" name="kelurahan" value="{{ old('kelurahan') }}" required autocomplete="kelurahan">
    
                                    @error('kelurahan')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="kecamatan" class="col-md-3 offset-md-1 col-form-label text-md-left">kecamatan</label>
    
                                <div class="col-md-6">
                                    <input id="kecamatan" type="kecamatan" class="form-control @error('kecamatan') is-invalid @enderror" name="kecamatan" value="{{ old('kecamatan') }}" required autocomplete="kecamatan">
    
                                    @error('kecamatan')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="kab_kota" class="col-md-3 offset-md-1 col-form-label text-md-left">Kabupaten/Kota</label>
    
                                <div class="col-md-6">
                                    <input id="kab_kota" type="kab_kota" class="form-control @error('kab_kota') is-invalid @enderror" name="kab_kota" value="{{ old('kab_kota') }}" required autocomplete="kab_kota">
    
                                    @error('kab_kota')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="kode_pos" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode Pos</label>
    
                                <div class="col-md-6">
                                    <input id="kode_pos" type="kode_pos" class="form-control @error('kode_pos') is-invalid @enderror" name="kode_pos" value="{{ old('kode_pos') }}" required autocomplete="new-kode_pos">
    
                                    @error('kode_pos')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="telp" class="col-md-3 offset-md-1 col-form-label text-md-left">Telepon</label>
    
                                <div class="col-md-6">
                                    <input id="telp" type="telp" class="form-control @error('telp') is-invalid @enderror" name="telp" value="{{ old('telp') }}" required autocomplete="new-telp">
    
                                    @error('telp')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                        
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Tambah
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pemilik/edit.blade.php
@extends('layouts.app')

{{-- isi @yield('content') --}}
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Data</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="card-body">
                        <form method="POST" action="{{ "/pemilik/$data->id" }}">
                            @method('put')
                            @csrf
                            
                            <div class="form-group row">
                                <label for="kode" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode</label>
    
                                <div class="col-md-6">
                                    <input id="kode" type="text" class="form-control @error('kode') is-invalid @enderror" name="kode" value="{{ $data->kode }}" required autocomplete="kode" autofocus>
    
                                    @error('kode')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    

                            <div class="form-group row">
                                <label for="nama" class="col-md-3 offset-md-1 col-form-label text-md-left">Nama</label>
    
                                <div class="col-md-6">
                                    <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ $data->nama }}" required autocomplete="nama" autofocus>
    
                                    @error('nama')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="alamat" class="col-md-3 offset-md-1 col-form-label text-md-left">Alamat</label>
    
                                <div class="col-md-6">
                                    <input id="alamat" type="alamat" class="form-control @error('alamat') is-invalid @enderror" name="alamat" value="{{ $data->alamat }}" required autocomplete="alamat">
    
                                    @error('alamat')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="kelurahan" class="col-md-3 offset-md-1 col-form-label text-md-left">kelurahan</label>
    
                                <div class="col-md-6">
                                    <input id="kelurahan" type="kelurahan" class="form-control @error('kelurahan') is-invalid @enderror" name="kelurahan" value="{{ $data->kelurahan }}" required autocomplete="kelurahan">
    
                                    @error('kelurahan')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="kecamatan" class="col-md-3 offset-md-1 col-form-label text-md-left">kecamatan</label>
    
                                <div class="col-md-6">
                                    <input id="kecamatan" type="kecamatan" class="form-control @error('kecamatan') is-invalid @enderror" name="kecamatan" value="{{ $data->kecamatan }}" required autocomplete="kecamatan">
    
                                    @error('kecamatan')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="kab_kota" class="col-md-3 offset-md-1 col-form-label text-md-left">Kabupaten/Kota</label>
    
                                <div class="col-md-6">
                                    <input id="kab_kota" type="kab_kota" class="form-control @error('kab_kota') is-invalid @enderror" name="kab_kota" value="{{ $data->kab_kota }}" required autocomplete="kab_kota">
    
                                    @error('kab_kota')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="kode_pos" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode Pos</label>
    
                                <div class="col-md-6">
                                    <input id="kode_pos" type="kode_pos" class="form-control @error('kode_pos') is-invalid @enderror" name="kode_pos" value="{{ $data->kode_pos }}" required autocomplete="new-kode_pos">
    
                                    @error('kode_pos')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="telp" class="col-md-3 offset-md-1 col-form-label text-md-left">Telepon</label>
    
                                <div class="col-md-6">
                                    <input id="telp" type="telp" class="form-control @error('telp') is-invalid @enderror" name="telp" value="{{ $data->telp }}" required autocomplete="new-telp">
    
                                    @error('telp')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                        
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Ubah
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pemilik/index.blade.php
@extends('layouts.app')

{{-- isi @yield('content') --}}
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">List Data</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="row text-right">
                        <div class="col-lg-12">
                            <a href="/pemilik/create" class="btn btn-primary btn-sm">
                              Tambah Data
                            </a>
                        </div>
                    </div>

                    <div class="row ml-1">   
                        <table border=1 cellpadding="10">
                            <thead style="text-align:center">
                                <th>No</th>
                                <th>Kode</th>
                                <th>Nama</th>
                                <th>Alamat</th>
                                <th>Telepon</th>
                                <th>Aksi</th>
                            </thead>
                            <tbody>
                            @foreach ($data as $dt)
                                <tr>
                                    <td>{{ $loop->iteration }} </td>   
                                    <td>{{ $dt->kode }} </td>   
                                    <td>{{ $dt->nama }} </td>   
                                    <td>{{ $dt->alamat }} </td>   
                                    <td>{{ $dt->telp }} </td>   
                                  
                                    <td>
                                      <a href={{"pemilik/$dt->id/edit"}} class="btn btn-warning btn-sm">Edit</a> 
                                      <form action={{"/pemilik/$dt->id"}} method="POST" class="d-inline">
                                        @method('delete')
                                        @csrf
                                          <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Yakin?')">Hapus</button>
                                      </form>
                                      <a href={{"pemilik/$dt->id"}} class="btn btn-primary btn-sm" >Detail</a>
                                    </td>  
                                </tr> 
                            @endforeach  
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pemilik/show.blade.php
@extends('layouts.app')

{{-- isi @yield('content') --}}
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Detail Data</div>

                <div class="card-body">
                 

                    <div class="card-body">
                        <form >
                            
                            <div class="form-group row">
                                <label for="kode" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode </label>
                                
                                <label for="kode" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->kode }} </label>
                            </div>

                            <div class="form-group row">
                                <label for="nama" class="col-md-3 offset-md-1 col-form-label text-md-left">Nama </label>
                                
                                <label for="nama" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->nama }} </label>
                            </div>

                            <div class="form-group row">
                                <label for="alamat" class="col-md-3 offset-md-1 col-form-label text-md-left">Alamat </label>
                                
                                <label for="alamat" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->alamat }} </label>
                            </div>

                            <div class="form-group row">
                                <label for="kelurahan" class="col-md-3 offset-md-1 col-form-label text-md-left">Kelurahan </label>
                                
                                <label for="kelurahan" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->kelurahan }} </label>
                            </div>

                            <div class="form-group row">
                                <label for="kecamatan" class="col-md-3 offset-md-1 col-form-label text-md-left">Kecamatan </label>
                                
                                <label for="kecamatan" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->kecamatan }} </label>
                            </div>
                            <div class="form-group row">
                                <label for="kab_kota" class="col-md-3 offset-md-1 col-form-label text-md-left">Kabupaten/Kota </label>
                                
                                <label for="kab_kota" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->kab_kota }} </label>
                            </div>
                            <div class="form-group row">
                                <label for="kode_pos" class="col-md-3 offset-md-1 col-form-label text-md-left">Kode Pos </label>
                                
                                <label for="kode_pos" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->kode_pos }} </label>
                            </div>
                            <div class="form-group row">
                                <label for="telp" class="col-md-3 offset-md-1 col-form-label text-md-left">Telepon </label>
                                
                                <label for="telp" class="col-md-3 offset-md-1 col-form-label text-md-left">: {{ $data->telp }} </label>
                            </div>
    
                        
                            <div class="form-group row mb-0">
                               
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection